on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}      
      - run: npm install
      - run: npm update caniuse-lite browserslist
#      - run: npm test
      - run: npm run build --if-present
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1          
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
#      -
#        name: Docker Build
#        run: |
#            docker build . # will run buildx        
      - name: Log into ACR
        uses: azure/docker-login@v1
        with:
          login-server: tmtestcr.azurecr.io #mycontainer.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker build
        run: |
          docker build . -t tmtestcr.azurecr.io/angularjspoc:${{ github.sha }}
          docker push tmtestcr.azurecr.io/angularjspoc:${{ github.sha }} 